spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/happy_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root          # 로컬 MySQL 계정
    password: password    # 로컬 MySQL 비번

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계라 자동 반영
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 8080
